services:
  neko:
    image: "ghcr.io/m1k1o/neko/chromium:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    cap_add:
      - SYS_ADMIN
    ports:
      - "8000:8080"
      - "52000-52100:52000-52100/udp"
    volumes:
      - /opt/neko/profile:/home/neko/.config/chromium
      - /opt/neko/downloads:/home/neko/Downloads
    environment:
      NEKO_DESKTOP_SCREEN: '1024x768@30'
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: 'fiap'
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: '2406'
      NEKO_WEBRTC_EPR: 52000-52100
      NEKO_WEBRTC_ICELITE: 1
      NEKO_WEBRTC_NAT1TO1: "${NEKO_WEBRTC_NAT1TO1}"
