---
- name: Instalar Azure CLI no Ubuntu
  hosts: azure_hosts
  become: true

  tasks:
    - name: Instalar dependências
      apt:
        name:
          - ca-certificates
          - curl
          - apt-transport-https
          - lsb-release
          - gnupg
        state: present
        update_cache: yes

    - name: Importar chave GPG da Microsoft
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Adicionar repositório do Azure CLI
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"
        state: present
        filename: azure-cli

    - name: Instalar azure-cli
      apt:
        name: azure-cli
        state: present
        update_cache: yes
