---
- name: Instalar e configurar Code Server no Ubuntu 22.04
  hosts: code_server
  become: true

  vars:
    code_server_user: ubuntu
    code_server_version: "4.89.1"
    code_server_port: 8099
    code_server_password: "fiap"  # Altere conforme necessário

  tasks:
    - name: Instalar dependências
      apt:
        name: [curl, wget, gnupg, software-properties-common]
        update_cache: yes

    - name: Baixar Code Server
      get_url:
        url: "https://github.com/coder/code-server/releases/download/v{{ code_server_version }}/code-server_{{ code_server_version }}_amd64.deb"
        dest: /tmp/code-server.deb

    - name: Instalar Code Server
      apt:
        deb: /tmp/code-server.deb

    - name: Criar diretório de configuração
      file:
        path: "/home/{{ code_server_user }}/.config/code-server"
        state: directory
        owner: "{{ code_server_user }}"
        group: "{{ code_server_user }}"
        mode: 0755

    - name: Criar arquivo config.yaml
      copy:
        dest: "/home/{{ code_server_user }}/.config/code-server/config.yaml"
        content: |
          bind-addr: 0.0.0.0:{{ code_server_port }}
          auth: password
          password: "{{ code_server_password }}"
          cert: false
        owner: "{{ code_server_user }}"
        group: "{{ code_server_user }}"
        mode: 0600

    - name: Criar arquivo de configurações globais (settings.json)
      copy:
        dest: "/home/{{ code_server_user }}/.local/share/code-server/User/settings.json"
        content: |
          {
            "files.exclude": {
              "**/.*": true
            },
            "workbench.colorTheme": "Default Dark+"
          }
        owner: "{{ code_server_user }}"
        group: "{{ code_server_user }}"
        mode: 0644

    - name: Habilitar e iniciar o serviço code-server
      systemd:
        name: code-server@{{ code_server_user }}
        enabled: yes
        state: started
