---
# https://docs.ansible.com/ansible/2.9/modules/modules_by_category.html
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#playbooks-conditionals
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#playbooks-loops

  - name: Instalar o Docker
    hosts: all
    become: yes
    tasks:
        # PRE-REQS DO UBUNTU
        - name: Instalar pré-reqs (ubuntu)
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - software-properties-common
            state: present
            update_cache: true
          when: ansible_os_family == "Debian"
        - name: Adicionar Docker GPG key (ubuntu)
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
          when: ansible_os_family == "Debian"
        - name: Adicionar Docker repo (ubuntu)
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu focal stable
            state: present
          when: ansible_os_family == "Debian"

        # INSTALL
        - name: Instalar o Docker via amazon-linux-extras no Amazon Linux 2
          shell: |
            amazon-linux-extras install docker -y
          when: (ansible_os_family == "RedHat") and (ansible_distribution_version == "2")

        - name: Instalar o Docker via dfm no Amazon Linux 2023
          become: yes
          ansible.builtin.package:
            name: 
             - docker
            #state: latest
            state: present
            disable_gpg_check: yes
            lock_timeout: 180
          when: (ansible_os_family == "RedHat") and (ansible_distribution_version == "2023")

        - name: Instalar o Docker via apt (ubuntu)
          become: yes
          apt:
            name:
              - docker-ce
              - docker-ce-cli 
              - containerd.io 
              - docker-buildx-plugin 
              - docker-compose-plugin
            state: present
            update_cache: true
            cache_valid_time: 3600
            force_apt_get: true
          register: apt_action
          retries: 100
          until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
          when: ansible_os_family == "Debian"

        - name: Restartar o Docker service
          service:
            name: docker
            state: restarted
            enabled: yes
          become: yes

        - name: Adicionar o usuario ec2-user ao grupo docker
          user:
            name: ec2-user
            groups: docker
            append: yes
          become: yes
          when: ansible_os_family == "RedHat"

        - name: Adicionar o usuario ubuntu ao grupo docker
          user:
            name: ubuntu
            groups: docker
            append: yes
          become: yes
          when: ansible_os_family == "Debian"
          
# https://github.com/docker/compose/issues/7472#issuecomment-749993557
# https://stackoverflow.com/a/65612078/2378095
  - name: Instalar o docker-compose
    hosts: all
    become: yes
    tasks:
        - name: download docker-compose
          shell: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.35.1/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          args:
            executable: /bin/bash
