---
# https://docs.ansible.com/ansible/2.9/modules/modules_by_category.html
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#playbooks-conditionals
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#playbooks-loops
  - name: Verificar ferramentas
    hosts: all
    tasks:
        - name: Verificar Python
          shell: |
            printf "\n\n xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx \n"
            printf "\n\n\tVerificando as instações:\n\n"
            printf "\n\n\tDEV TOOLS:\n\n"
            printf "\n\tJAVA:\n"
            java -version
            javac -version
            printf "\n\tMAVEN:\n"
            mvn -version
            printf "\n\tSPRING:\n"
            spring --version
            printf "\n\tPYTHON:\n"
            python3 --version
            printf "\n\tPIP:\n"
            pip3 --version
            printf "\n\n\tOPS TOOLS:\n\n"
            printf "\n\tDOCKER:\n"
            sudo docker version
            docker-compose --version
            printf "\n\tAWSCLI:\n"
            aws --version
            printf "\n\tTERRAFORM:\n"
            terraform --version
            #printf "\n\tANSIBLE:\n"
            #ansible --version
            printf "\n\tMINIKUBE:\n"
            minikube version
            printf "\n\tKUBECTL:\n"
            kubectl version --client
            printf "\n\tHELM:\n"
            helm version -c
            printf "\n\tEXIBE DISCO :\n"
            df -mh | grep dev
            #liberando acesso externo
            printf "\n\tAPLICANDO ULTIMAS CONFIGURAÇÕES:\n"
            #sudo apt-get -y install jq > /dev/null
            source ~/environment/config/pacotes.sh
            printf "\n\tMAVEN:\n"
            mvn -version
          args:
            executable: /bin/bash
        #  register: out
        #  
        #- debug: resultado=out.stdout_lines
        
          register: log
        
        - debug: msg="{{ log.stdout_lines }}"
