  - name: Executar Code Server em container
    hosts: all
    #become: yes
    tasks:
      # https://docs.ansible.com/ansible/2.9/modules/docker_container_module.html
      # https://hub.docker.com/r/linuxserver/code-server
      - name: Code server container run
        docker_container:
          name: codeserver
          image: lscr.io/linuxserver/code-server:latest
          ports:
            - "8443:8443"
          env:
            PUID: "1000"
            PGID: "1000"
            PASSWORD: "fiap"
          volumes:
            - /opt/codeserver:/config
            - /home/ubuntu:/config/workspace
          restart_policy: unless-stopped
