  - name: Executar Code Server em container
    hosts: all
    #become: yes
    tasks:
      # Configurar o settings.json
      - name: Criar diretorio vazio Code Server
        ansible.builtin.file:
          path: ~/.local/share/code-server/User/
          state: directory
          mode: '0755'
          
      - name: Configurar o settings.json para o Code Server
        ansible.builtin.copy:
          dest: "~/.local/share/code-server/User/settings.json"
          content: |
            {
              "files.exclude": {
                "**/.*": true
              },
              "workbench.colorTheme": "Default Dark+"
            }

      # https://docs.ansible.com/ansible/2.9/modules/docker_container_module.html
      # https://hub.docker.com/r/linuxserver/code-server
      - name: Executar o Code server em conteiner
        docker_container:
          name: codeserver
          image: lscr.io/linuxserver/code-server:latest
          ports:
            - "8099:8443"
          env:
            PUID: "1000"
            PGID: "1000"
            PASSWORD: "fiap"
            TZ: "America/Sao_Paulo"
          volumes:
            - /opt/codeserver:/config
            - /home/ubuntu:/config/workspace
          restart_policy: unless-stopped
