---
# https://docs.ansible.com/ansible/2.9/modules/modules_by_category.html
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#playbooks-conditionals
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#playbooks-loops
  - name: Instalar o Docker
    hosts: all
    become: yes
    tasks:
        - name: Desabilitar GPGCheck certs
          # yum repo configuration file, the line gpgcheck=1 indicates that GPG checking should be done for all packages in this repository
          shell: "sed -i 's|gpgcheck = 1|gpgcheck = 0|' /etc/yum.repos.d/amzn2-extras.repo"
          when: ansible_os_family == "RedHat"
        - name: Instalar via amazon-linux-extras
          #shell: "sudo yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo"
          #shell: "yum-config-manager --disable kubernetes"
          shell: "amazon-linux-extras install docker -y"
          when: ansible_os_family == "RedHat"
        - name: Instalar dependencias
          ansible.builtin.package:
          #yum:
            name: 
             - docker
            state: latest

        - name: Restartar o Docker service
          service:
            name: docker
            state: restarted
            enabled: yes
          become: yes

        - name: Adicionar o usuario ec2-user ao grupo docker
          user:
            name: ec2-user
            groups: docker
            append: yes
          become: yes
          when: ansible_os_family == "RedHat"

        - name: Adicionar o usuario ubuntu ao grupo docker
          user:
            name: ubuntu
            groups: docker
            append: yes
          become: yes
          when: ansible_os_family == "Debian"
          
# https://github.com/docker/compose/issues/7472#issuecomment-749993557
# https://stackoverflow.com/a/65612078/2378095
  - name: Instalar o docker-compose
    hosts: all
    become: yes
    tasks:
        - name: download docker-compose
          shell: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          args:
            executable: /bin/bash
