---
# https://docs.ansible.com/ansible/2.9/modules/modules_by_category.html
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#playbooks-conditionals
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#playbooks-loops
  - name: Instalação das ferramentas DEV Java
    hosts: all
    tasks:
        - name: Instalar Java e Maven
          become: yes
          shell: |
            sudo amazon-linux-extras install java-openjdk11 -y
            wget https://www-eu.apache.org/dist/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz
            sudo tar xf apache-maven-*.tar.gz -C /opt
            rm -f apache-maven-3.8.1-bin.tar.gz
            sudo ln -s /opt/apache-maven-3.8.1 /opt/maven
            sudo cat >> /etc/environment <<EOL
            export JAVA_HOME=/usr/lib/jvm/jre-11-openjdk
            export M2_HOME=/opt/maven
            export MAVEN_HOME=/opt/maven
            export SONAR_SCANNER_OPTS="-Xmx512m"
            EOL
            echo 'export PATH=/opt/maven/bin:${PATH}' | sudo tee -a /etc/profile
          args:
            executable: /bin/bash

        - name: Verificar Java e Maven
          shell: |
            java --version
            #mvn --version
          args:
            executable: /bin/bash
          register: log
        
        - debug: msg="{{ log.stdout }}"
